### ISSUE TITLE
Juno should be defaulting to the coding conventions used in base Julia

### ISSUE THREAD

**Issue by tkelman** [JuliaIDE/Julia-LT#167]
namely 4-space indent instead of 2

ref https://github.com/JuliaLang/julia/pull/10054#issuecomment-72983942

**Comment by dpsanders** [comment]
+1

**Comment by tkelman** [comment]
LT Juno is dead, closing.

Atom based Juno is going to need to do this though. Not acceptable to default to tabs that don't adhere to base Julia's coding conventions.
