### ISSUE TITLE
Julia extremely slow on Windows 7 32bit "Julia + Juno IDE bundle"

### ISSUE THREAD

**Issue by JonWel** [JuliaIDE/Julia-LT#183]
A friend tried this bundle: https://junolab.s3.amazonaws.com/release/1.0.0/juno-windows-x32.zip
on her Windows 7 32 bit system and the speed was really catastrophic at execution.
Simple operations like `3*6+4` can take more than a second to be executed (tested with `Ctrl+Enter`), and trying to run the tutorial script (with `Pkg.update()` and 'Pkg.add("Gadfly")') is a real pain (didn't even finish the update after several minutes).

I tried to reproduce it with an old XP 32bit SP2 and SP3 (under a virtual machine), but the `juno.exe` is not recognised as a valid Win32 application. `/resources/app/julia/bin/julia.exe` works correctly.
I also tried with Vista 32 bit and it says it cannot find `RegisterTouchWindow` in `USER32.dll`.

Does other people have the same problem under Windows 32-bit systems? Is there a workaround?

**Comment by one-more-minute** [comment]
Atom-Shell only supports 7 and up, but x32 Windows 7 should be fine. I haven't been able to reproduce this myself, unfortunately, so I'm not sure how much I can do.

Although the slowness of the package manager is a separate issue which is known, I think.

You could try seeing what's slow from the terminal ("open a terminal repl" command) and report any issues you still see there to the Julia repo.

**Comment by JonWel** [comment]
Oh, I didn't know it only support Windows 7 and later, that explain why my own tests fails (XP and Vista). That may be great to add this information in the Julia download page (http://julialang.org/downloads/) but I guess this is not the right place for that.

I'll have to wait to see my friend again to check if the slowness is on Julia or Light table side (all my windows since 7 are 64 bit).

(I don't know if it worth I open a new thread, but under linux, there seems to be an unexpected "(" on the node extension, both 32 and 64 bit affected )

**Comment by JonWel** [comment]
There has been quite a lot of changes since I opened it and I don't have the possibility to reproduce, so I think there is no need to keep this issue open.
